# Generated by Django 2.2.2 on 2019-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmusic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_country',
        ),
        migrations.AddField(
            model_name='music',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
