# Generated by Django 2.2.2 on 2019-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmusic', '0003_auto_20191112_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(null=True, upload_to='music_image/'),
        ),
    ]
