# Generated by Django 2.2.2 on 2019-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmusic', '0009_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
