# Generated by Django 2.2.2 on 2019-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmusic', '0010_music_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(null=True),
        ),
    ]
